### ISSUE TITLE
Ejercicio 2 - E

### ISSUE THREAD

**Issue by Sofiortiz** [ISPC-TST-SENSORES-y-ACTUADORES-2023/tarea4-grupo-2#5]
¿Cómo implementaría un sensor inteligente de altitud?

**Comment by joacorta** [comment]
realizado en commit #12  b6a4427ee67f1d3cf4d32d27c5b6c1f760639739

**Comment by joacorta** [comment]
realizado en commit #12  b6a4427ee67f1d3cf4d32d27c5b6c1f760639739
